# 配置端口号和默认路径
server:
  port: 8080
  servlet:
    context-path: /

# 配置连接数据库的四大金刚，thymeleaf模板的前缀和后缀
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql:///pethome?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver

# 配置别名 + 扫描mapper映射文件
mybatis:
  type-aliases-package: org.fgbokg.org.domain, org.fgbokg.org.query,
                        org.fgbokg.user.domain, org.fgbokg.user.query,
                        org.fgbokg.sm.domain, org.fgbokg.sm.query
  mapper-locations: classpath:org/fgbokg/mapper/*.xml    # 约定大于配置，可以不写

# 日志
logging:
  level:
    org:
      fgbokg: trace
    root: info
